name: 'Fast-forward merge PR'
on:
  pull_request_review:
    types: [submitted]

jobs:
  merge:
    if: github.event.review.state == 'approved' && contains(github.event.review.body, '/merge')   
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Rebase
        run: |
          git fetch
          git rebase origin/${{ github.event.pull_request.base.ref }} && git push -f
      - name: Fast-forward merge
        run: |
          git fetch
          git checkout ${{ github.event.pull_request.base.ref }}
          git merge --ff-only origin/${{ github.event.pull_request.head.ref }}
          git push
